# Generated by Django 3.2.3 on 2021-06-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo nota:')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion:')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion:')),
                ('fecha_finalizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha finalizacion:')),
            ],
        ),
    ]
