# Generated by Django 3.2.3 on 2021-06-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareaSorpresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='estado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado:'),
        ),
    ]
